services:
  server:
    # image: ghcr.io/socheatsok78-lab/swarmshicorp-vault:1.16
    image: swarmshicorp-vault:local
    hostname: "vault-{{.Task.Slot}}.local"
    command: server
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
        mode: host
    networks:
      - vault_netwok
    environment:
      - VAULT_LOG_LEVEL=${VAULT_LOG_LEVEL:-trace}
      # Integrated storage (Raft) backend
      - VAULT_RAFT_NODE_ID
      - VAULT_RAFT_PATH=${VAULT_RAFT_PATH:-/vault/file}
      # # Specifies the address (full URL) to advertise to other Vault servers in the cluster for client redirection.
      - VAULT_API_INTERFACE
      - VAULT_API_ADDR
      # # # Specifies the address (full URL) that should be used for other cluster members to connect to this node when in High Availability mode.
      - VAULT_CLUSTER_INTERFACE
      - VAULT_CLUSTER_ADDR
      # # # Specifies the address (full URL) that should be used when clients are redirected to this node when in High Availability mode.
      - VAULT_REDIRECT_INTERFACE
      - VAULT_REDIRECT_ADDR=vault-{{.Task.Slot}}.local
    volumes:
      - vault-file:/vault/file
      - vault-logs:/vault/logs
    cap_add:
      - IPC_LOCK
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        order: stop-first
        monitor: 120s

volumes:
  vault-file:
  vault-logs:

networks:
  vault_netwok:
    driver: overlay
    driver_opts:
      encrypted: "true"
