services:
  server:
    image: ghcr.io/socheatsok78-lab/swarmshicorp-vault:1.16
    command: server
    environment:
      # Specifies the identifier for the Vault cluster
      - VAULT_CLUSTER_NAME
      # Specifies the address (full URL) to advertise to other Vault servers in the cluster for
      # client redirection to this node when in High Availability mode. (default to VAULT_CLUSTER_ADDR value)
      # You can set either one of these values, the priority is as follows:
      - VAULT_API_ADDR
      - VAULT_REDIRECT_ADDR
      # DO NOT CHANGE THIS VALUES BELOW
      # Internal Docker Swarm configurations
      - VAULT_LOG_LEVEL=${VAULT_LOG_LEVEL:-info}
      - VAULT_RAFT_NODE_ID={{.Node.ID}}
      - VAULT_ADVERTISE_ADDR=http://{{.Node.Hostname}}:8200
      - VAULT_CLUSTER_ADDR=http://{{.Node.ID}}.vault.svc.cluster.local:8201
    hostname: "{{.Node.ID}}.vault.svc.cluster.local"
    networks:
      - vault_netwok
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
        mode: host
    volumes:
      - vault-file:/vault/file
      - vault-logs:/vault/logs
    cap_add:
      - IPC_LOCK
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        order: stop-first
        monitor: 120s

volumes:
  vault-file:
  vault-logs:

networks:
  vault_netwok:
    driver: overlay
    driver_opts:
      encrypted: "true"
